pool:
  vmImage: ubuntu-latest

stages:
- stage: Build
  jobs:
  - job: Build
    steps:
    - script: echo "hello to my first Build"

- stage: dev_deploy
  jobs:
  - deployment: dev_deploy
    strategy:
      runOnce:
        deploy:
          steps:
          - script: echo "hello, dev world !!!"
